on: [push, pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: actions/git-branch-name-action@v1
      - name: Echo the branch name
        run: echo "The time was ${GIT_BRANCH_NAME}"
